# Übung Lineare Algebra (10 Punkte)

Diese kleine Übung soll die grundlegenden arithmetischen Opertationen auf Vektoren und Matrizen wiederholen. Bitte implementieren Sie die notwendigen Methoden in der Datei _ak1163051/lineare_algebra.py_ auf Basis von Listen und verifizieren Sie ihre Implementierungen mit der entsprechenden _numpy_-Operation, sofern dies möglich ist im Notebook. Ein Beispiel für die Notebook imple


In [1]:
# Initialization of basic modules and global parameters... 
from ak1163051.lineare_algebra import *
import numpy as np
import random

# create vectors a and b with 10 digits between 0-255
vec_a = random.sample(range(255), 10)
vec_b = random.sample(range(255), 10)

print ("Vektor a: ", vec_a)
print ("Vektor b: ", vec_b)

Vektor a:  [168, 51, 31, 234, 41, 163, 75, 76, 150, 72]
Vektor b:  [88, 166, 22, 79, 163, 47, 126, 225, 161, 188]


## Addition und Subtraktion von Vektoren

Berechnen Sie Betrag und Differenz von Vektoren nach folgendem Prinzip:

<img src="ak1163051/pics/add_vector.svg", width=250>

<img src="ak1163051/pics/sub_vector.svg", width=250>

In [2]:
# Addition
add_result = vector_add(vec_a, vec_b)
print ("Result of vector addition:", add_result)
print ("Are the operations arithmetically equal?", np.array_equal(add_result, np.add(vec_a,vec_b)))

# Subtraction - please implement the methode in lineare_algebra.py 
sub_result = vector_sub(vec_a, vec_b)
print ("Result of vector subtraction:", sub_result)
print ("Are the operations arithmetically equal?", np.array_equal(sub_result, np.subtract(vec_a,vec_b)))

Result of vector addition: [256, 217, 53, 313, 204, 210, 201, 301, 311, 260]
Are the operations arithmetically equal? True
Result of vector subtraction: [80, -115, 9, 155, -122, 116, -51, -149, -11, -116]
Are the operations arithmetically equal? True


## Multiplikation von Vektoren mit einem Skalar (0,5 Punkt)

Berechenen Sie die Multiplikation von einem Skalar und einem Vektoren nach folgendem Prinzip:

<img src="ak1163051/pics/scalar_vector.svg", width=200>

In [3]:
s = 42

r = s * np.array(vec_a)
r_ = vector_scalar_mul(s, vec_a)

assert np.array_equal(r, r_ )

1:	[7056 2142 1302 9828 1722 6846 3150 3192 6300 3024]
2:	[7056, 2142, 1302, 9828, 1722, 6846, 3150, 3192, 6300, 3024]


## Skalarprodukt (dot product) von Vektoren (1 Punkte)

Berechnen Sie das Skalarprodukt von zwei Vektoren nach folgendem Prinzip:

<img src="ak1163051/pics/inner_product_vector.svg", width=400>

In [4]:
# your code (numpy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

r = np.dot(vec_a, vec_b)
r_ =  vector_dot(vec_a, vec_b)

assert r == r_ 

1:	120998
2:	120998


## Erzeugen eine Matrix (1 Punkte)
Erzuegen Sie mit Hilfe einer Methode eine Matrix mit der Dimension 10x10 von Zufallswerten zwischen 0 und 255.

In [5]:
mat_a = create_random_matrix(10,3)
print (f"Matrix A: \n{np.array(mat_a)}")

Matrix A: 
[[223  61  22 253 177 104 170  97 210 237]
 [ 11 219 197 171  35 186 156 126 239 251]
 [249 176 213  66  55 160 170  68  85 189]]


## Vektor-Matrix-Multiplikation (1 Punkte)

Berechnen Sie das Produkt aus Vektor a und Matrix A nach folgendem Prinzip:

<img src="ak1163051/pics/mult_vector_matrix.svg", width=400>

Merken Sie sich, dass die Dimensionen hierfür eine Vorraussetzung bilden.

<img src="ak1163051/pics/mult_vector_matrix_dim.png", width=300>

In [13]:
#%debug
# your code (numpy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

r = np.multiply(np.array(mat_a), np.array(vec_a)  )
r_ = matrix_vector_mul(mat_a, vec_a)

assert np.array_equal(r, r_ )

## Transponente einer Matrix (1 Punkte)

Manipulieren Sie die Matrix A, sodass die Transponente entsteht, siehe:
    
<img src="ak1163051/pics/trans_matrix_01.svg", width=250>    
<img src="ak1163051/pics/trans_matrix_02.svg", width=250>    

In [10]:
# your code (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.transpose.html)
assert np.array_equal(matrix_transpose(mat_a), np.array(mat_a).T)

---

## Verwendete Bibliotek



In [ ]:
# %load ak1163051/lineare_algebra.py
""" Some functions for basic linear algebra operations based on python lists. """

from random import randint


def vector_add(a, b):
    assert len(a) == len(b)
    return [x + b[i] for i, x in enumerate(a)]


def vector_sub(a, b):
    return [x - b[i] for i, x in enumerate(a)]


def vector_scalar_mul(r, a):
    return [r * x for x in a]


def vector_dot(a, b):
    assert len(a) == len(b)
    return sum(a[i] * x for i, x in enumerate(b))


def create_random_matrix(n, m):
    return [[randint(0, 255) for _n in range(n)] for _m in range(m)]


def matrix_vector_mul(mat, vec):
    E = []
    for c in mat: 
        E.append([r*vec[i] for i, r in enumerate(c)])
    return E
        
    
def matrix_transpose(a):
    if not isinstance(a[0], list):
        return a
    s = len(a[0])
    return [[row[i] for row in a] for i in range(s)]